-- DROP TABLE docs;
CREATE TABLE APEX_APP.docs (
    id NUMBER GENERATED by default on null as IDENTITY,
    content CLOB,
    summary CLOB,
    translation CLOB,
    summary_embed vector,
    resource_name varchar2(1024), -- Parent file that caused the event to trigger.
    path varchar2(1024),    
    content_type varchar2(256),
    region varchar2(256),    
    application_name varchar2(256),
    author varchar2(256),
    creation_date varchar2(256),    
    modified varchar2(256),    
    other1 varchar2(1024),    
    other2 varchar2(1024),    
    other3 varchar2(1024),    
    parsed_by varchar2(256),    
    title varchar2(1024),
    source_type varchar2(256)
);
alter table "APEX_APP"."DOCS" add constraint "DOCS_PK" primary key ( "ID" );

CREATE TABLE APEX_APP."DOCS_LANGCHAIN" (
    "ID" RAW(16) DEFAULT SYS_GUID(), 
	"TEXT" CLOB, 
	"METADATA" JSON, 
	"EMBEDDING" VECTOR, 
	PRIMARY KEY ("ID")
);
CREATE INDEX APEX_APP.docs_langchain_index on APEX_APP.docs_langchain( text ) indextype is ctxsys.context;  

CREATE VECTOR INDEX APEX_APP.docs_langchain_hnsw_idx ON APEX_APP.docs_langchain(embedding) ORGANIZATION INMEMORY NEIGHBOR GRAPH DISTANCE COSINE WITH TARGET ACCURACY 95;

-- Helper view for debugging
create view APEX_APP.V_DOCS_LANGCHAIN as
    select 
        JSON_VALUE(metadata,'$.path') as URL,            
        metadata,
        JSON_VALUE(metadata,'$.doc_id') as DOCID, 
        JSON_VALUE(metadata,'$.file_name') as TITLE, 
        text as BODY, 
        id as CHUNKID, 
        TO_NUMBER(JSON_VALUE(metadata,'$.page_label')) as PAGE_NUMBERS      
    from APEX_APP.docs_langchain;

-- DROP TABLE docs_chunck;
/*
CREATE TABLE APEX_APP.docs_chunck (
    id NUMBER GENERATED by default on null as IDENTITY,
    doc_id number,
    fileblob BLOB, -- Null when the file is outside of the DB, allow upload of files with for ex APEX
    content CLOB,
    translation CLOB,
    embed vector(1024),
    resource_name varchar2(256),    
    path varchar2(1024),    
    content_type varchar2(256),
    region varchar2(256),    
    page integer,
    char_start integer,
    char_end integer,
    summary CLOB
);
alter table "APEX_APP"."DOCS_CHUNCK" add constraint "DOCS_CHUNCK_PK" primary key ( "ID" );
alter table "APEX_APP"."DOCS_CHUNCK" add constraint "DOCS_FK" foreign key ( "DOC_ID" ) references "APEX_APP.DOCS" ( "ID" ) on delete cascade;
create index APEX_APP.docs_index on APEX_APP.docs_langchain( text ) indextype is ctxsys.context;  
*/

CREATE OR REPLACE FUNCTION APEX_APP.embedText( c VARCHAR2 ) 
RETURN clob IS 
    resp DBMS_CLOUD_TYPES.resp; 
    b CLOB; 
    s CLOB; 
    start_vector number;
    stop_vector number;
    region varchar2(128);
    compartment_ocid varchar2(128);    
    genai_embed_model varchar2(128);    
BEGIN 
    select value into region from AI_AGENT_RAG_CONFIG where key='region';
    select value into compartment_ocid from AI_AGENT_RAG_CONFIG where key='compartment_ocid';    
    select value into genai_embed_model from AI_AGENT_RAG_CONFIG where key='genai_embed_model';    
    resp := DBMS_CLOUD.send_request( 
        credential_name => 'OCI$RESOURCE_PRINCIPAL', 
        uri =>'https://inference.generativeai.'|| region || '.oci.oraclecloud.com/20231130/actions/embedText',
        method => 'POST', 
        body => UTL_RAW.cast_to_raw( JSON_OBJECT (
            'compartmentId' VALUE compartment_ocid,
            'servingMode' VALUE JSON_OBJECT( 'modelId' VALUE genai_embed_model, 
                                             'servingType' VALUE 'ON_DEMAND' ),   
            'inputs' VALUE JSON_ARRAY( c ),
            'truncate' VALUE 'START'
        ))    
    ); 
    b := DBMS_CLOUD.get_response_text(resp); 
    -- JSON PARSING does not work....
    start_vector := instr(b,'[[')+1;
    stop_vector := instr(b, ']]')+1;
    select substr(b,start_vector, stop_vector-start_vector) into s; 
    return s;
END embedText; 
/

CREATE OR REPLACE FUNCTION APEX_APP.RETRIEVAL_FUNC (p_query IN VARCHAR2,top_k IN NUMBER) RETURN SYS_REFCURSOR IS
    v_results SYS_REFCURSOR;
    cleaned_query varchar2(4096);
BEGIN
    -- Simple Vector query 
    OPEN v_results FOR
        select 
            JSON_VALUE(metadata,'$.doc_id') as DOCID, 
            text as BODY, 
            vector_distance(embedding, to_vector(embedText( p_query ))) AS SCORE,
            id as CHUNKID, 
            JSON_VALUE(metadata,'$.file_name') as TITLE, 
            JSON_VALUE(metadata,'$.path') as URL,
            '[' || JSON_VALUE(metadata,'$.page_label') || ']' as PAGE_NUMBERS    
            -- NUMBER_TT( TO_NUMBER(JSON_VALUE(metadata,'$.page_label')) ) as PAGE_NUMBERS   
            -- TO_NUMBER(1) as PAGE_NUMBERS   
        from docs_langchain
        -- where JSON_VALUE(metadata,'$.doc_id') in (select to_char(id) from docs order by vector_distance(summary_embed,  to_vector(embedText( 'what is jazz' ))) fetch first 3 rows only)
        order by score 
        fetch first top_k rows only;

    -- Hybrid Search query (30 Lexical/ 70 Vector)
    -- Oracle Text score: 0 - 100.0 (higher is better)
    -- Vector distance : 0 - 1.0 (closer is better)
/*    
    -- Clean up the query string to avoid issue with the CONTAINS(xxx), error like ORA-29902 ORA-30600 DRG-50901
    cleaned_query := REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(p_query, '!', ' '), '?', ' '), '#', ' '), '>', ' '), '<', ' ');
    AI_AGENT.LOG( 'P_QUERY', p_query );

    OPEN v_results FOR
        WITH text_search AS (
            SELECT id, score(99)/100 as score FROM docs_langchain
            WHERE CONTAINS(text, cleaned_query, 99)>0 order by score(99) DESC FETCH FIRST top_k ROWS ONLY
        ),
        vector_search AS (

            SELECT id, vector_distance(embedding, to_vector(embedText( p_query ))) AS vector_distance
            FROM docs_langchain
        )
        SELECT 
            JSON_VALUE(metadata,'$.doc_id') as docid, 
            text as BODY,
            (0.3 * ts.score + 0.7 * (1 - vs.vector_distance)) AS score,
            o.id as CHUNKID,
            JSON_VALUE(metadata,'$.file_name') as TITLE, 
            JSON_VALUE(metadata,'$.path') as URL,
            JSON_VALUE(metadata,'$.page_label') as page_numbers             
        FROM docs_langchain o
        JOIN text_search ts ON o.id = ts.id
        JOIN vector_search vs ON o.id = vs.id
        ORDER BY score DESC
        FETCH FIRST top_k ROWS ONLY;
*/
    RETURN v_results;
end RETRIEVAL_FUNC;
/

-- Admin function 
CREATE OR REPLACE FUNCTION RETRIEVAL_FUNC (p_query IN VARCHAR2,top_k IN NUMBER) RETURN SYS_REFCURSOR IS
begin
    return APEX_APP.RETRIEVAL_FUNC( p_query, top_k);
end;    
/

/*
insert into DOCS_CHUNCK(
       DOC_ID,
       FILENAME,
       PATH,
       Content,
       embed)
values( 1, 'oracle', 'https://www.oracle.com', 'hello world', embedtext('hello_world'));

-- Check the RETRIEVAL_FUNC function
-- Display the DOCID and SCORE

DECLARE
  v_results SYS_REFCURSOR;
  v_docid VARCHAR2(100);
  v_body VARCHAR2(4000);
  v_score NUMBER;
  v_chunck_id VARCHAR2(4000);
  v_title VARCHAR2(4000);
  v_url VARCHAR2(4000);
  v_page_numbers VARCHAR2(4000);
  p_query VARCHAR2(100) := 'what is jazz';
  top_k NUMBER := 10;
BEGIN
  v_results := RETRIEVAL_FUNC(p_query, top_k);
 
  DBMS_OUTPUT.PUT_LINE('DOCID   | SCORE  | URL     | page_numbers');
  DBMS_OUTPUT.PUT_LINE('--------|--------|---------|------------------');
 
  LOOP
    FETCH v_results INTO v_docid, v_body, v_score, v_chunck_id, v_title, v_url, v_page_numbers;
    EXIT WHEN v_results%NOTFOUND;
 
    DBMS_OUTPUT.PUT_LINE(v_docid || ' | ' || v_score || ' | ' || v_url || ' | ' || v_page_numbers);
  END LOOP;
 
  CLOSE v_results;
END; 

*/

exit 
